name: workflow1
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print something1
        run: echo "Hi This is my first workflow"
      - name: print something2
        run: echo "Hi This is my second workflow"
