name: workflow1
on: workflow_dispatch
# on:
  # push:
    # branches: [main]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print USERNAME
        run: |
          echo "my username is ${{ secrets.USERNAME }}"
      - name: print PASSWORD
        run: echo "my password is ${{ secrets.PASSWORD }}"
